# Generated by Django 4.2.7 on 2023-11-23 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='company',
            new_name='Company',
        ),
    ]
